using System;
using System.Reflection;
using SailwindCoop.Runtime;

namespace SailwindCoop.Sync
{
    /// <summary>Declared inputs in the audited game DLL. Binding is not relay coverage.</summary>
    internal static class InteractionActionCatalog
    {
        internal sealed class Input
        {
            internal readonly string TypeName, Method;
            internal readonly string[] Parameters;
            internal Input(string type, string method, params string[] parameters)
            { TypeName = type; Method = method; Parameters = parameters; }
        }
        internal static readonly string[] Types = {
            "Anchor",
            "BilgePump",
            "BoatDamageWaterButton",
            "BoatLadder",
            "CargoCarrierButton",
            "CargoStorageUIButton",
            "CrateInventoryButton",
            "CurrencyExchangeUIButton",
            "CurrencySwitchButton",
            "DockPushCol",
            "EconomyUIButton",
            "GoPointerButton",
            "GPButtonAntiAliasing",
            "GPButtonAutosaveToggle",
            "GPButtonBed",
            "GPButtonBoatPushCol",
            "GPButtonBuyItem",
            "GPButtonControlToggle",
            "GPButtonDayLogDay",
            "GPButtonDockMooring",
            "GPButtonExtraMenus",
            "GPButtonInterface",
            "GPButtonInventorySlot",
            "GPButtonKeybinding",
            "GPButtonLightQuality",
            "GPButtonListedMission",
            "GPButtonLogMode",
            "GPButtonMapZoom",
            "GPButtonMissionListBack",
            "GPButtonMissionListPage",
            "GPButtonMissionListWorld",
            "GPButtonOnsenEntrance",
            "GPButtonPortMissions",
            "GPButtonPurchaseBoat",
            "GPButtonRatlines",
            "GPButtonResetKeybindings",
            "GPButtonResolutionUI",
            "GPButtonRopeWinch",
            "GPButtonSailPusher",
            "GPButtonScreenResolution",
            "GPButtonSetMission",
            "GPButtonSettingsCheckbo",
            "GPButtonSliderVolume",
            "GPButtonSteeringWheel",
            "GPButtonTargetFramerate",
            "GPButtonTavernSleep",
            "GPButtonTrapdoor",
            "GPButtonWindowMode",
            "HullDamageButton",
            "MooringRopeLengthAdjuster",
            "MouseoverTextTrigger",
            "PickupableBoatMooringRope",
            "PickupableItem",
            "ShipItem",
            "ShipItemBed",
            "ShipItemBottle",
            "ShipItemBroom",
            "ShipItemChipLog",
            "ShipItemClock",
            "ShipItemCompass",
            "ShipItemCrate",
            "ShipItemElixir",
            "ShipItemFishingHook",
            "ShipItemFishingRod",
            "ShipItemFoldable",
            "ShipItemFood",
            "ShipItemHammer",
            "ShipItemHangable",
            "ShipItemInkSet",
            "ShipItemKettle",
            "ShipItemKnife",
            "ShipItemLampHook",
            "ShipItemLanternFuel",
            "ShipItemLight",
            "ShipItemOakum",
            "ShipItemOar",
            "ShipItemPipe",
            "ShipItemQuadrant",
            "ShipItemRandomElixir",
            "ShipItemSalt",
            "ShipItemScroll",
            "ShipItemSoup",
            "ShipItemSpyglass",
            "ShipItemStove",
            "ShipItemStoveFuel",
            "ShipItemTea",
            "ShipItemTobacco",
            "ShipItemTotem",
            "ShipyardButton",
            "ShipyardDocuments",
            "StartMenuButton",
            "TradeReceiptsUIButton",
            "WindTotemOrb"
        };
        internal static readonly Input[] Inputs = {
            new Input("Anchor", "ExtraFixedUpdate"),
            new Input("BilgePump", "Update"),
            new Input("BilgePump", "OnActivate", "GoPointer"),
            new Input("BilgePump", "OnUnactivate", "GoPointer"),
            new Input("BoatDamageWaterButton", "ExtraLateUpdate"),
            new Input("BoatDamageWaterButton", "OnItemClick", "PickupableItem"),
            new Input("BoatLadder", "Update"),
            new Input("BoatLadder", "OnActivate"),
            new Input("CargoCarrierButton", "OnActivate"),
            new Input("CargoStorageUIButton", "ExtraLateUpdate"),
            new Input("CargoStorageUIButton", "OnActivate", "GoPointer"),
            new Input("CrateInventoryButton", "OnActivate", "GoPointer"),
            new Input("CurrencyExchangeUIButton", "OnActivate"),
            new Input("CurrencySwitchButton", "Update"),
            new Input("CurrencySwitchButton", "OnActivate"),
            new Input("DockPushCol", "ExtraFixedUpdate"),
            new Input("EconomyUIButton", "OnActivate"),
            new Input("GoPointerButton", "OnActivate"),
            new Input("GoPointerButton", "OnActivate", "GoPointer"),
            new Input("GoPointerButton", "OnActivateHit", "RaycastHit"),
            new Input("GoPointerButton", "OnAltActivate"),
            new Input("GoPointerButton", "OnAltActivate", "GoPointer"),
            new Input("GoPointerButton", "OnUnactivate"),
            new Input("GoPointerButton", "OnUnactivate", "GoPointer"),
            new Input("GoPointerButton", "OnAltHeld"),
            new Input("GoPointerButton", "OnAltHeld", "GoPointer"),
            new Input("GoPointerButton", "OnItemClick", "PickupableItem"),
            new Input("GoPointerButton", "LateUpdate"),
            new Input("GoPointerButton", "FixedUpdate"),
            new Input("GoPointerButton", "ExtraLateUpdate"),
            new Input("GoPointerButton", "ExtraFixedUpdate"),
            new Input("GPButtonAntiAliasing", "OnActivate"),
            new Input("GPButtonAutosaveToggle", "OnActivate"),
            new Input("GPButtonBed", "OnActivate"),
            new Input("GPButtonBoatPushCol", "ExtraFixedUpdate"),
            new Input("GPButtonBuyItem", "OnActivate"),
            new Input("GPButtonBuyItem", "OnItemClick", "PickupableItem"),
            new Input("GPButtonControlToggle", "OnActivate"),
            new Input("GPButtonDayLogDay", "OnActivate"),
            new Input("GPButtonDockMooring", "OnItemClick", "PickupableItem"),
            new Input("GPButtonExtraMenus", "OnActivate"),
            new Input("GPButtonInterface", "OnActivate"),
            new Input("GPButtonInventorySlot", "OnActivate"),
            new Input("GPButtonInventorySlot", "OnActivate", "GoPointer"),
            new Input("GPButtonInventorySlot", "OnItemClick", "PickupableItem"),
            new Input("GPButtonKeybinding", "OnActivate"),
            new Input("GPButtonKeybinding", "Update"),
            new Input("GPButtonLightQuality", "OnActivate"),
            new Input("GPButtonListedMission", "OnActivate"),
            new Input("GPButtonLogMode", "OnActivate"),
            new Input("GPButtonMapZoom", "OnActivate"),
            new Input("GPButtonMissionListBack", "OnActivate"),
            new Input("GPButtonMissionListPage", "OnActivate"),
            new Input("GPButtonMissionListWorld", "OnActivate"),
            new Input("GPButtonOnsenEntrance", "OnActivate"),
            new Input("GPButtonPortMissions", "OnActivate"),
            new Input("GPButtonPurchaseBoat", "OnActivate"),
            new Input("GPButtonRatlines", "OnActivateHit", "RaycastHit"),
            new Input("GPButtonResetKeybindings", "OnActivate"),
            new Input("GPButtonResolutionUI", "OnActivate"),
            new Input("GPButtonRopeWinch", "OnActivate", "GoPointer"),
            new Input("GPButtonRopeWinch", "OnUnactivate", "GoPointer"),
            new Input("GPButtonRopeWinch", "Update"),
            new Input("GPButtonSailPusher", "ExtraFixedUpdate"),
            new Input("GPButtonScreenResolution", "OnActivate"),
            new Input("GPButtonSetMission", "OnActivate"),
            new Input("GPButtonSettingsCheckbo", "OnActivate"),
            new Input("GPButtonSliderVolume", "OnActivateHit", "RaycastHit"),
            new Input("GPButtonSteeringWheel", "OnActivate", "GoPointer"),
            new Input("GPButtonSteeringWheel", "OnUnactivate", "GoPointer"),
            new Input("GPButtonSteeringWheel", "ExtraLateUpdate"),
            new Input("GPButtonSteeringWheel", "ExtraFixedUpdate"),
            new Input("GPButtonTargetFramerate", "OnActivate"),
            new Input("GPButtonTavernSleep", "OnActivate"),
            new Input("GPButtonTrapdoor", "OnActivate"),
            new Input("GPButtonWindowMode", "OnActivate"),
            new Input("HullDamageButton", "OnItemClick", "PickupableItem"),
            new Input("HullDamageButton", "ExtraLateUpdate"),
            new Input("MooringRopeLengthAdjuster", "OnAltActivate", "GoPointer"),
            new Input("MooringRopeLengthAdjuster", "OnPickup"),
            new Input("MooringRopeLengthAdjuster", "OnDrop"),
            new Input("MooringRopeLengthAdjuster", "Update"),
            new Input("MooringRopeLengthAdjuster", "OnScroll", "Single"),
            new Input("MouseoverTextTrigger", "ExtraLateUpdate"),
            new Input("PickupableBoatMooringRope", "Update"),
            new Input("PickupableBoatMooringRope", "ExtraLateUpdate"),
            new Input("PickupableBoatMooringRope", "OnPickup"),
            new Input("PickupableBoatMooringRope", "OnAltActivate", "GoPointer"),
            new Input("PickupableBoatMooringRope", "OnDrop"),
            new Input("PickupableItem", "OnPickup"),
            new Input("PickupableItem", "OnDrop"),
            new Input("PickupableItem", "OnScroll", "Single"),
            new Input("ShipItem", "ExtraFixedUpdate"),
            new Input("ShipItem", "Update"),
            new Input("ShipItem", "OnPickup"),
            new Input("ShipItem", "OnDrop"),
            new Input("ShipItem", "OnItemClick", "PickupableItem"),
            new Input("ShipItem", "OnAltActivate"),
            new Input("ShipItemBed", "OnAltActivate"),
            new Input("ShipItemBottle", "OnItemClick", "PickupableItem"),
            new Input("ShipItemBottle", "OnAltActivate"),
            new Input("ShipItemBottle", "OnAltHeld"),
            new Input("ShipItemBottle", "OnDrop"),
            new Input("ShipItemBottle", "ExtraLateUpdate"),
            new Input("ShipItemBroom", "OnAltActivate"),
            new Input("ShipItemBroom", "ExtraLateUpdate"),
            new Input("ShipItemChipLog", "Update"),
            new Input("ShipItemChipLog", "ExtraLateUpdate"),
            new Input("ShipItemChipLog", "OnAltActivate"),
            new Input("ShipItemChipLog", "OnAltHeld"),
            new Input("ShipItemClock", "ExtraLateUpdate"),
            new Input("ShipItemClock", "OnAltActivate"),
            new Input("ShipItemCompass", "OnScroll", "Single"),
            new Input("ShipItemCompass", "OnDrop"),
            new Input("ShipItemCompass", "ExtraLateUpdate"),
            new Input("ShipItemCrate", "OnPickup"),
            new Input("ShipItemCrate", "OnAltActivate", "GoPointer"),
            new Input("ShipItemElixir", "OnAltActivate"),
            new Input("ShipItemFishingRod", "OnItemClick", "PickupableItem"),
            new Input("ShipItemFishingRod", "Update"),
            new Input("ShipItemFishingRod", "ExtraLateUpdate"),
            new Input("ShipItemFishingRod", "OnAltActivate"),
            new Input("ShipItemFishingRod", "OnAltHeld"),
            new Input("ShipItemFishingRod", "OnScroll", "Single"),
            new Input("ShipItemFoldable", "OnItemClick", "PickupableItem"),
            new Input("ShipItemFoldable", "OnAltActivate"),
            new Input("ShipItemFood", "OnItemClick", "PickupableItem"),
            new Input("ShipItemFood", "OnAltHeld"),
            new Input("ShipItemFood", "ExtraLateUpdate"),
            new Input("ShipItemHammer", "OnAltActivate"),
            new Input("ShipItemHammer", "OnAltHeld"),
            new Input("ShipItemHangable", "OnPickup"),
            new Input("ShipItemKettle", "OnItemClick", "PickupableItem"),
            new Input("ShipItemKettle", "OnAltActivate"),
            new Input("ShipItemKettle", "ExtraLateUpdate"),
            new Input("ShipItemKnife", "OnAltActivate"),
            new Input("ShipItemKnife", "ExtraLateUpdate"),
            new Input("ShipItemLampHook", "OnPickup"),
            new Input("ShipItemLampHook", "OnItemClick", "PickupableItem"),
            new Input("ShipItemLight", "OnPickup"),
            new Input("ShipItemLight", "OnDrop"),
            new Input("ShipItemLight", "OnItemClick", "PickupableItem"),
            new Input("ShipItemLight", "OnAltActivate"),
            new Input("ShipItemLight", "ExtraLateUpdate"),
            new Input("ShipItemOakum", "OnAltActivate"),
            new Input("ShipItemOar", "ExtraLateUpdate"),
            new Input("ShipItemOar", "OnAltActivate"),
            new Input("ShipItemOar", "OnAltHeld"),
            new Input("ShipItemPipe", "ExtraLateUpdate"),
            new Input("ShipItemPipe", "OnAltHeld"),
            new Input("ShipItemPipe", "OnItemClick", "PickupableItem"),
            new Input("ShipItemQuadrant", "OnAltActivate"),
            new Input("ShipItemQuadrant", "OnDrop"),
            new Input("ShipItemQuadrant", "ExtraLateUpdate"),
            new Input("ShipItemRandomElixir", "OnAltActivate"),
            new Input("ShipItemSalt", "OnItemClick", "PickupableItem"),
            new Input("ShipItemScroll", "OnScroll", "Single"),
            new Input("ShipItemScroll", "OnPickup"),
            new Input("ShipItemScroll", "OnDrop"),
            new Input("ShipItemSoup", "OnItemClick", "PickupableItem"),
            new Input("ShipItemSoup", "OnAltActivate"),
            new Input("ShipItemSoup", "OnAltHeld"),
            new Input("ShipItemSoup", "ExtraLateUpdate"),
            new Input("ShipItemSpyglass", "OnPickup"),
            new Input("ShipItemSpyglass", "OnDrop"),
            new Input("ShipItemSpyglass", "OnAltActivate"),
            new Input("ShipItemSpyglass", "OnScroll", "Single"),
            new Input("ShipItemStove", "OnPickup"),
            new Input("ShipItemStove", "OnItemClick", "PickupableItem"),
            new Input("ShipItemStove", "ExtraLateUpdate"),
            new Input("ShipItemTea", "OnItemClick", "PickupableItem"),
            new Input("ShipItemTotem", "OnAltHeld"),
            new Input("ShipItemTotem", "ExtraLateUpdate"),
            new Input("ShipyardButton", "ExtraLateUpdate"),
            new Input("ShipyardButton", "OnActivate"),
            new Input("ShipyardDocuments", "OnActivate"),
            new Input("ShipyardDocuments", "Update"),
            new Input("StartMenuButton", "OnActivate"),
            new Input("StartMenuButton", "ExtraLateUpdate"),
            new Input("TradeReceiptsUIButton", "OnActivate"),
            new Input("WindTotemOrb", "OnDrop"),
            new Input("WindTotemOrb", "Update")
        };
        // Required entries: a vanished override must not hide behind an empty base method.
        internal static readonly Input[] HostOnlyInputs = {
            new Input("GPButtonAutosaveToggle", "OnActivate")
        };
        internal static PatchHookCatalog Inspect(Assembly game)
        {
            var catalog = new PatchHookCatalog();
            foreach (string name in Types) catalog.InspectType(game.GetType(name), name);
            foreach (var input in Inputs)
                catalog.InspectNames(game.GetType(input.TypeName), input.TypeName, input.Method, input.Parameters);
            return catalog;
        }
    }
    internal static class ItemActionCatalog
    {
        internal sealed class Route
        {
            internal readonly InteractionActionCatalog.Input Input;
            internal readonly string Domain, Purpose;
            internal Route(InteractionActionCatalog.Input input, string domain, string purpose)
            { Input = input; Domain = domain; Purpose = purpose; }
        }
        internal static readonly Route[] Routes = {
            new Route(new InteractionActionCatalog.Input("ShipItem", "OnAltActivate"), "Shop", "Shopkeeper.TryToSellItem; actor wallet/UI"),
            new Route(new InteractionActionCatalog.Input("ShipItemBed", "OnAltActivate"), "Sleep", "Addressed EnterBed lifecycle; unsold shop branch stays local"),
            new Route(new InteractionActionCatalog.Input("ShipItemBottle", "OnAltActivate"), "Shop", "Shopkeeper.TryToSellItem"),
            new Route(new InteractionActionCatalog.Input("ShipItemBottle", "OnAltHeld"), "Items", "Drink result; personal needs stay local"),
            new Route(new InteractionActionCatalog.Input("ShipItemBroom", "OnAltActivate"), "Items", "Broom pulse; actual Cleaner UV goes through Dirt textures"),
            new Route(new InteractionActionCatalog.Input("ShipItemChipLog", "OnAltActivate"), "Instrument poses", "Buffered bobber/rope and final state"),
            new Route(new InteractionActionCatalog.Input("ShipItemChipLog", "OnAltHeld"), "Instrument poses", "Buffered bobber/rope and final state"),
            new Route(new InteractionActionCatalog.Input("ShipItemClock", "OnAltActivate"), "Special item visuals", "Absolute lid target"),
            new Route(new InteractionActionCatalog.Input("ShipItemCrate", "OnAltActivate", "GoPointer"), "Local", "Local crate UI; membership/unseal use dedicated hooks"),
            new Route(new InteractionActionCatalog.Input("ShipItemElixir", "OnAltActivate"), "Item results", "Consume after personal effect"),
            new Route(new InteractionActionCatalog.Input("ShipItemFishingRod", "OnAltActivate"), "Instrument poses", "Buffered bobber/line/fish visual; CollectFish via Items"),
            new Route(new InteractionActionCatalog.Input("ShipItemFishingRod", "OnAltHeld"), "Instrument poses", "Actual held bobber/line stream"),
            new Route(new InteractionActionCatalog.Input("ShipItemFoldable", "OnAltActivate"), "Items", "Absolute FoldableState"),
            new Route(new InteractionActionCatalog.Input("ShipItemFood", "OnAltHeld"), "Items", "EatFood consume; personal needs stay local"),
            new Route(new InteractionActionCatalog.Input("ShipItemHammer", "OnAltActivate"), "Items", "Target NailItem result"),
            new Route(new InteractionActionCatalog.Input("ShipItemHammer", "OnAltHeld"), "Items", "Target NailItem result"),
            new Route(new InteractionActionCatalog.Input("ShipItemKettle", "OnAltActivate"), "Shop", "Only unsold shop branch; recipe is T5"),
            new Route(new InteractionActionCatalog.Input("ShipItemKnife", "OnAltActivate"), "Item results", "CutFood compound lifecycle; typed FoodState"),
            new Route(new InteractionActionCatalog.Input("ShipItemLight", "OnAltActivate"), "Lights", "Light target; stable ID remains T2/T4"),
            new Route(new InteractionActionCatalog.Input("ShipItemOakum", "OnAltActivate"), "Item results", "Compound hull delta/resource"),
            new Route(new InteractionActionCatalog.Input("ShipItemOar", "OnAltActivate"), "Items", "Local stroke reset; force captured by no-arg held hook"),
            new Route(new InteractionActionCatalog.Input("ShipItemOar", "OnAltHeld"), "Items", "Actual rowing impulse"),
            new Route(new InteractionActionCatalog.Input("ShipItemPipe", "OnAltHeld"), "Item simulation", "Personal smoke, ordered resource/content state"),
            new Route(new InteractionActionCatalog.Input("ShipItemQuadrant", "OnAltActivate"), "Special item visuals", "Absolute inspecting target"),
            new Route(new InteractionActionCatalog.Input("ShipItemRandomElixir", "OnAltActivate"), "Item results", "Consume after local RNG; shared rainbow result"),
            new Route(new InteractionActionCatalog.Input("ShipItemSoup", "OnAltActivate"), "Shop", "Only unsold shop branch; recipe/drink is T5"),
            new Route(new InteractionActionCatalog.Input("ShipItemSoup", "OnAltHeld"), "Item results", "Compound soup use/recipe"),
            new Route(new InteractionActionCatalog.Input("ShipItemSpyglass", "OnAltActivate"), "Local", "Observer root pose; actor camera/zoom"),
            new Route(new InteractionActionCatalog.Input("ShipItemTotem", "OnAltHeld"), "Item results", "FinishCast shared effect/resource")
        };
        internal static PatchHookCatalog Inspect(Assembly game)
        {
            var catalog = new PatchHookCatalog();
            foreach (var route in Routes)
            {
                string pending = route.Domain == "" ? route.Purpose :
                    route.Domain == "Local" || PatchHealth.StateOf(route.Domain) == PatchHealthState.Ok ? null :
                    "required " + route.Domain + " hooks not healthy; " + route.Purpose;
                var input = route.Input;
                catalog.InspectNames(game.GetType(input.TypeName), input.TypeName, input.Method, input.Parameters, pending);
            }
            return catalog;
        }
    }
}
